#!/bin/bash

rm -rvf *-topo.json build/*.json
mkdir -p build

echo 'convert to geojson' 
shp2json --encoding utf-8 -n build/lpr_000a21a_e.shp \
  | ndjson-map '(d.pruid = d.properties.PRUID, d)' \
  | ndjson-map -r rp=reproject -r epsg '(d.geometry = rp.toWgs84(d.geometry, 3347, epsg.epsg), d)' \
  > build/pr-geo.json

chmod a-x build/pr-geo.json

# echo 'build topojson' 
# geo2topo -q 1e5 -n prs=build/pr-geo-4326.json \
#   | toposimplify -f -s 1e-7 \
#   | topomerge nation=prs \
#   > build/pr-auto-topo.json