#!/bin/bash

rm -rvf *-topo.json build/*.json
mkdir -p build
touch build/pr-geo-4326.json

echo 'convert to geojson' 
shp2json --encoding utf-8 -n build/lpr_000a21a_e.shp \
  | ndjson-map '(d.pruid = d.properties.PRUID, d)' \
  > build/pr-geo.json

echo 'reproject from 3347 to 4326'
while IFS="" read -r f || [ -n "$f" ]
do 
  echo $f | reproject --use-epsg-io --from=EPSG:3347 --to=EPSG:4326 >> build/pr-geo-4326.json
  echo >> build/pr-geo-4326.json
done < build/pr-geo.json

echo 'build topojson' 
geo2topo -q 1e5 -n prs=build/pr-geo-4326.json \
  | toposimplify -f -s 1e-7 \
  | topomerge nation=prs \
  > build/pr-auto-topo.json