#!/bin/bash

rm -rvf *-t.json
mkdir -p build

ROOTURL=https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/files-fichiers/
CD='lcd_000b21a_e'


if [ ! -f build/$CD.shp ]; then
  curl -o build/$CD.zip $ROOTURL$CD.zip
  unzip build/$CD.zip -d build
  chmod a-x build/$CD.*
fi

geo2topo -q 1e5 -n cds=<( \
  shp2json --encoding utf-8 -n build/$CD.shp \
    | ndjson-filter '(d.properties.PRUID == "10")' \
    | ndjson-map '(d.prid = d.properties.PRUID, d)' \
    | ndjson-map '(d.cdid = d.properties.CDUID, delete d.properties, d)') \
  | toposimplify -f -s 1 \
  | topomerge prs=cds -k 'd.prid' \
  > cd-t.json