#!/bin/bash

rm -rvf *-10m.json
mkdir -p build

if [ ! -f build/cb_2017_us_county_5m.shp ]; then
    curl -o build/cb_2017_us_county_5m.zip 'https://www2.census.gov/geo/tiger/GENZ2017/shp/cb_2017_us_county_5m.zip'
    unzip -od build build/cb_2017_us_county_5m.zip cb_2017_us_county_5m.shp cb_2017_us_county_5m.dbf
    chmod a-x build/cb_2017_us_county_5m.*
fi

geo2topo -q 1e5 -n counties=<( \
    shp2json --encoding utf-8 -n build/cb_2017_us_county_5m.shp \
        | ndjson-filter '!("000$".test(d.properties.GEOID))' \
        | ndjson-map '(d.id = d.properties.GEOID, delete d.properties)') \
    | toposimplify -f -s 1e-7 \
    > counties-10m.json